name: Auto Squash Merge for env/dev

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
    branches:
      - 'env/dev'

jobs:
  auto-squash-settings:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    
    steps:
      - name: Enforce squash merge
        uses: actions/github-script@v6
        with:
          script: |
            // Only proceed if the base branch is env/dev
            if (context.payload.pull_request.base.ref === 'env/dev') {
              try {
                // Update PR to enable squash merging and disable other merge methods
                await github.rest.repos.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  allow_squash_merge: true,
                  allow_merge_commit: false,
                  allow_rebase_merge: false
                });
                
                // Add a comment to inform users about squash merge requirement
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  body: '📝 This PR targets `env/dev` branch and will be squash merged. All commits will be combined into a single commit.'
                });
              
              } catch (error) {
                console.error('Error setting up squash merge:', error);
                throw error;
              }
            }
